create database floresColas;
grant all privileges on floresColas.* to 'colas'@'%' identified by 'chisela';

create table floresColas.USERS (
	username VARCHAR(50),
	password VARCHAR(32), --encriptacion md5, md5('6vzR4EH')
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	date_of_birth DATE,
	genre VARCHAR(50),
	admin VARCHAR(50)
);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('emucklow0', md5('6vzR4EH'), 'Esme', 'Mucklow', '6/13/1939', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('ksalliss1', '49JipE', 'Kingsley', 'Salliss', '8/25/1988', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('kiddy2', '7RPryeOIupmP', 'Katy', 'Iddy', '9/17/1975', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('rdarrigo3', 'bNH41NIO3tQ5', 'Red', 'D''Arrigo', '11/20/1926', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('mkillingback4', 'SXiY0zv', 'Mitchael', 'Killingback', '10/11/1921', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('mmchenry5', 'NXPo4GIadi', 'Michaelina', 'McHenry', '8/14/2006', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('tputman6', 'n9E0z8dthu', 'Towny', 'Putman', '2/9/1948', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('twaldram7', 'buCKUteD', 'Tessa', 'Waldram', '11/13/1937', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('rwestgate8', 'VyRMtt', 'Richmond', 'Westgate', '3/5/1959', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('echiene9', 'JueIR1', 'Egan', 'Chiene', '5/19/1958', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('srippingalla', 'cjm3MSEUqng', 'Shaine', 'Rippingall', '2/7/1960', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('lrollb', 'uqg6rzINaQ', 'Lauritz', 'Roll', '1/23/1929', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('mbettamc', 'fC6rz14Sv', 'Meridith', 'Bettam', '12/25/1976', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('cbengled', 'efcVrjbLx', 'Cleavland', 'Bengle', '2/10/1999', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('gdallywatere', 'TbgpivUkKGl', 'Georgia', 'Dallywater', '8/12/1930', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('jleslyf', 'ZXmA11wjkEY', 'Judd', 'Lesly', '3/20/1966', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('shodjettsg', 'pB9NXGqv', 'Spike', 'Hodjetts', '12/14/1978', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('ahassonh', 'JD3PmD5I1vAL', 'Alva', 'Hasson', '1/23/1989', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('lgoodbarnei', 'gTQYmq', 'Lyndy', 'Goodbarne', '9/10/1943', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('bdeverilj', 'J1bFj1', 'Beniamino', 'Deveril', '9/25/1934', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('bdoulk', 'dHfZ8EzBs0M', 'Bartholemy', 'Doul', '4/7/1971', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('cvellal', 'LVv8Oge', 'Carolus', 'Vella', '12/16/1921', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('bholleranm', 'yHp5DoZz5vG', 'Berry', 'Holleran', '1/24/1927', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('nsamtern', 'Cev5AHC2', 'Natividad', 'Samter', '6/15/1920', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('mwhitcombeo', 'zeoZ9pO', 'Marlie', 'Whitcombe', '9/15/1996', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('eantonuttip', 'hBU9RGp4du', 'Everard', 'Antonutti', '9/23/1999', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('rdoddemeadeq', '1CcVeMiGp', 'Richardo', 'Doddemeade', '10/27/1977', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('blutenr', 'DGlwNjR5', 'Bourke', 'Luten', '11/22/1981', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('lkubiczeks', '6sOEakhm3RE', 'Lorette', 'Kubiczek', '4/3/1933', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('wcreavint', 'glErCPMuU', 'Winifield', 'Creavin', '10/23/1933', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('mkasheru', 'OjHz1NzPo', 'Madelene', 'Kasher', '1/14/1960', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('cfogdenv', 'ie03bYzfz', 'Cheslie', 'Fogden', '4/20/1988', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('blamartinew', 'uItxXEBHT8', 'Babbette', 'Lamartine', '9/22/1996', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('apharrox', '7OTcCWBE4Kx', 'Angela', 'Pharro', '12/23/1968', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('lbakeyy', 'ITE2f0M8', 'Lindi', 'Bakey', '3/4/2008', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('lwilcez', 'bLyF5JxB0GmE', 'Leontyne', 'Wilce', '1/2/2003', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('jbukowski10', 'm6qah0K', 'Joellen', 'Bukowski', '12/3/1988', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('blates11', 'CdqNwhhU', 'Bennie', 'Lates', '6/30/1953', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('jfindon12', 'yxOS4hzWthO', 'Justin', 'Findon', '3/31/2007', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('ccapnerhurst13', 'Ts7hjt', 'Carce', 'Capnerhurst', '12/8/1947', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('lelwell14', 'oZnl4Fxv5iV', 'Lindsy', 'Elwell', '8/8/1931', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('sstansbury15', 'sO9OGF91aA', 'Scotty', 'Stansbury', '3/6/1936', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('jwillment16', 'HzwOegYY', 'Jay', 'Willment', '11/3/1928', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('crichemont17', 'HgwT0Gc8YSr', 'Charin', 'Richemont', '10/2/2002', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('sfilipczak18', 'c0KiuXCphFD', 'Shannen', 'Filipczak', '12/7/1995', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('mceschelli19', 'UIe1drs37tgu', 'Mayer', 'Ceschelli', '11/27/1994', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('fivanyushkin1a', 'g661SWIv', 'Friederike', 'Ivanyushkin', '3/27/1953', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('bnorthidge1b', 'XLX0HRAc', 'Blondy', 'Northidge', '10/14/1953', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('icousen1c', 'a49xyrwbn', 'Isidora', 'Cousen', '2/1/1967', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('rdupree1d', 'PaUwmHiyQ1t7', 'Rowney', 'Dupree', '3/7/1959', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('ceasterling1e', 'ICS6zMyOsi', 'Christopher', 'Easterling', '5/4/1947', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('sbushell1f', 'C5zgROqzzejF', 'Sydney', 'Bushell', '11/23/1950', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('ospratling1g', 'CteDccHb4', 'Orville', 'Spratling', '6/15/2007', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('desmonde1h', '4GHdX0Ta3Sc', 'Dorette', 'Esmonde', '8/1/1933', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('imikalski1i', 'JZmyivSNX', 'Ignacio', 'Mikalski', '7/8/2005', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('ejennions1j', 'JqWJQsm', 'Emelita', 'Jennions', '6/21/1921', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('lgorler1k', 'QmVxtDv', 'Lutero', 'Gorler', '7/3/1950', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('stwopenny1l', 'HIV7eJM3jB', 'Shea', 'Twopenny', '11/14/1958', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('wdewitt1m', '34PxOg9Nxto', 'Wendye', 'De Witt', '12/20/1927', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('rmacvaugh1n', 'QKVvpfcAHESJ', 'Raina', 'MacVaugh', '5/7/1991', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('mcurling1o', '6s7TsCkpVTT1', 'Marianna', 'Curling', '4/24/1967', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('pswyer1p', 'E6k65l', 'Phoebe', 'Swyer', '1/12/1999', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('jhallihane1q', '1ATc9w9U', 'Janith', 'Hallihane', '10/26/1965', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('chearnden1r', 'J5pJkzWDU', 'Christel', 'Hearnden', '8/4/1982', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('rnewborn1s', 'plDSPsclB', 'Rowen', 'Newborn', '10/18/1998', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('kgurry1t', '8pSzjq', 'Katine', 'Gurry', '12/1/1970', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('mpues1u', '78aR81ZvL', 'Melissa', 'Pues', '3/26/1958', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('gescale1v', '4hdg44nQ1C', 'Gaby', 'Escale', '2/22/1940', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('gparrott1w', 'gg1oh0s', 'Gregoor', 'Parrott', '4/20/2000', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('rmickleborough1x', 'YIoXTd78rLN', 'Roby', 'Mickleborough', '12/19/1976', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('rrevett1y', 'adPsLybc', 'Reeba', 'Revett', '5/20/1995', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('alynthal1z', 'Aq9vxVvQA', 'Artemas', 'Lynthal', '12/10/1934', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('alansberry20', 'V5G2pSc8NH', 'Alejoa', 'Lansberry', '7/14/1954', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('hanscombe21', 'xeDvOafI8c', 'Hal', 'Anscombe', '1/10/1995', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('ahadland22', 'TmSYVXiIe', 'Abel', 'Hadland', '9/13/1935', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('gkochlin23', 'mC20gCIQ', 'Glen', 'Kochlin', '6/28/1936', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('lbea24', '87ut8CPTYF9g', 'Lucinda', 'Bea', '11/9/1922', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('bsomes25', 'RrabYBRE', 'Betteann', 'Somes', '4/1/1997', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('efrick26', 'F6GHyh', 'Elonore', 'Frick', '6/20/1953', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('fgoring27', 'svQ6eu5O', 'Freda', 'Goring', '5/21/1961', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('vfloresColas.SALEry28', 'q3s1EpE', 'Valentino', 'floresColas.SALEry', '5/6/1980', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('dkegley29', 'gcKp7ORHcM', 'Davine', 'Kegley', '7/12/1953', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('mlinnitt2a', 'L7x7C6', 'Matthieu', 'Linnitt', '9/2/1959', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('ooswick2b', 'oofxTwLc', 'Oran', 'Oswick', '12/10/1978', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('ckleint2c', 'v2Fblua', 'Clarke', 'Kleint', '6/30/1944', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('mtiler2d', '25wbMpDWcx', 'Merilee', 'Tiler', '3/23/2001', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('tcoleyshaw2e', 'BPMM2rO', 'Thorstein', 'Coleyshaw', '10/18/1943', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('sduckwith2f', 'YZzN8K1gv8Z', 'Sherry', 'Duckwith', '5/9/1993', 'Female', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('sdelicate2g', '4GfiJm', 'Sonny', 'Delicate', '1/9/1953', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('awing2h', 'NBeVRmDZ', 'Aube', 'Wing', '1/6/1981', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('mbridger2i', 'iJpY2cSCQOe', 'Marietta', 'Bridger', '7/22/1950', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('gchampionnet2j', 'nT3TfScFih', 'Gregory', 'Championnet', '5/10/1952', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('kkerner2k', '7Oq9ury', 'Khalil', 'Kerner', '3/22/1968', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('wjurges2l', 'ZH6lqixZvQw', 'Wren', 'Jurges', '10/6/1994', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('ncardall2m', 'U2xDXi2j0', 'Neall', 'Cardall', '4/28/1991', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('hkernoghan2n', 'ZLEkRnnY', 'Hagen', 'Kernoghan', '4/17/1957', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('tcicutto2o', '9GMTy8hpeRq9', 'Toddie', 'Cicutto', '5/17/1922', 'Male', true);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('ariddler2p', '2e5aei6dV5U', 'Arney', 'Riddler', '10/16/2002', 'Male', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('kokennavain2q', 'FWjllHMhu', 'Kala', 'O''Kennavain', '6/22/1993', 'Female', false);
insert into floresColas.USERS (username, password, first_name, last_name, date_of_birth, genre, admin) values ('lblaxter2r', 'wab3WY19U', 'Lacie', 'Blaxter', '11/1/1954', 'Female', false);

create table floresColas.COLOR (
	code VARCHAR(7),
	name VARCHAR(20),
	description VARCHAR(50)
);
insert into floresColas.COLOR (code, name, description) values ('#b79c30', 'Teal', 'Parmeliaceae');
insert into floresColas.COLOR (code, name, description) values ('#861610', 'Crimson', 'Saxifragaceae');
insert into floresColas.COLOR (code, name, description) values ('#4f6b83', 'Aquamarine', 'Rosaceae');
insert into floresColas.COLOR (code, name, description) values ('#1861a9', 'Orange', 'Empetraceae');
insert into floresColas.COLOR (code, name, description) values ('#7f2b4d', 'Indigo', 'Fagaceae');
insert into floresColas.COLOR (code, name, description) values ('#413558', 'Red', 'Asteraceae');
insert into floresColas.COLOR (code, name, description) values ('#0b45b2', 'Khaki', 'Strelitziaceae');
insert into floresColas.COLOR (code, name, description) values ('#a21e2a', 'Turquoise', 'Cyperaceae');
insert into floresColas.COLOR (code, name, description) values ('#5eb5c5', 'Goldenrod', 'Liliaceae');
insert into floresColas.COLOR (code, name, description) values ('#1346de', 'Fuscia', 'Poaceae');

create table floresColas.FLOWER (
	code INT,
	name VARCHAR(50) UNIQUE,
	description VARCHAR(50),
	price DECIMAL(5,2),
	color VARCHAR(50)
);

insert into floresColas.FLOWER (code, name, description, price, color) values (1, 'Yellow Asphodel', 'Narthecium americanum Ker Gawl.', 99.93, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, color) values (2, 'California Tickseed', 'Coreopsis californica (Nutt.) H. Sharsm. var. californica', 39.54, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, color) values (3, 'Narrowleaf Evening Primrose', 'Oenothera fruticosa L. ssp. tetragona (Roth) W.L. Wagner', 20.31, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, color) values (4, 'Lecidea Lichen', 'Lecidea myriocarpella (G. Merr.) Zahlbr.', 1.63, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, color) values (5, 'Epling''s Hedgenettle', 'Stachys eplingii J.B. Nelson', 10.93, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, color) values (6, '''ohi''a Lehua', 'Metrosideros polymorpha Gaudich. var. pseudorugosa Skottsb.', 58.69, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (7, 'Hairy Sensitive Pea', 'Chamaecrista pilosa (L.) Greene', 58.14, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (8, 'Coastal Plain Creepingoxeye', 'Wedelia fruticosa Jacq.', 87.03, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (9, 'Goldenthread', 'Cuscuta salina Engelm. var. papillata Yunck.', 85.82, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (10, 'Fall Tansyaster', 'Machaeranthera asteroides (Torr.) Greene', 75.42, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (11, 'Rattlesnakeweed', 'Hieracium venosum L.', 92.91, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (12, 'Rape', 'Brassica napus L.', 56.87, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (13, 'Beard Lichen', 'Usnea vainioi Mot.', 18.59, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (14, 'Synthlipsis', 'Synthlipsis A. Gray', 76.72, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (15, 'Eggyolk Lichen', 'Candelariella citrina de Lesd.', 3.59, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (16, 'Hawthorn', 'Crataegus L.', 11.76, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (17, 'Woody Goldenrod', 'Chrysoma pauciflosculosa (Michx.) Greene', 97.09, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (18, 'Stylophorum', 'Stylophorum Nutt.', 16.74, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (19, 'Wart Lichen', 'Porina salicina Müll. Arg.', 75.15, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (20, 'Dotted Lichen', 'Bacidia herbarum (Stizenb.) Arnold', 86.76, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (21, 'Twocrested Milkvetch', 'Astragalus bicristatus A. Gray', 5.41, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (22, 'Darrow''s Blueberry', 'Vaccinium darrowii Camp', 94.07, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (23, 'Giant Woollystar', 'Eriastrum densifolium (Benth.) H. Mason ssp. sanctorum (Milliken) H. Mason', 38.25, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (24, 'Rose Silene', 'Silene coeli-rosa (L.) Godr.', 28.76, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (25, 'Geyer''s Onion', 'Allium geyeri S. Watson', 25.92, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (26, 'Purple Threeawn', 'Aristida purpurea Nutt. var. purpurea', 87.95, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (27, 'Arctic Raspberry', 'Rubus arcticus L. ssp. stellatus (Sm.) B. Boivin', 92.61, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (28, 'Hairy Angelica', 'Angelica venenosa (Greenway) Fernald', 39.79, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (29, 'Lindheimer''s Indigo', 'Indigofera lindheimeriana Scheele', 3.1, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (30, 'Button Brittlebush', 'Encelia resinifera C. Clark ssp. resinifera', 97.34, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (31, 'Rusby''s Blazingstar', 'Mentzelia rusbyi Wooton', 92.64, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (32, 'Kerr''s Milkvetch', 'Astragalus kerrii Knight & Cully', 44.66, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (33, 'Tower Rockcress', 'Arabis glabra (L.) Bernh.', 99.44, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (34, 'Stinging Serpent', 'Cevallia Lag.', 75.69, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (35, 'Sandwort Microcalicium Lichen', 'Microcalicium arenarium (Hampe ex A. Massal.) Tibell', 89.42, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (36, 'Natal Indigo', 'Indigofera arrecta Hochst. ex A. Rich.', 39.77, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (37, 'Dovefoot Geranium', 'Geranium molle L.', 93.38, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (38, 'Relicina Lichen', 'Relicina eximbricata (Gyel.) Hale', 61.48, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (39, 'Island Sagebrush', 'Artemisia nesiotica P.H. Raven', 45.06, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (40, 'Littleseed Canarygrass', 'Phalaris minor Retz.', 18.42, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (41, 'Tea', 'Camellia sinensis (L.) Kuntze var. sinensis', 37.91, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (42, 'Fanleaf Fleabane', 'Erigeron flabellifolius Rydb.', 21.84, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (43, 'Compressed Entodon Moss', 'Entodon compressus (Hedw.) Müll. Hal.', 31.72, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (44, 'Climbing Bamboo', 'Chusquea abietifolia Griseb.', 79.94, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (45, 'Gray Clubawn Grass', 'Corynephorus canescens (L.) P. Beauv.', 73.93, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (46, 'Hall''s Milkvetch', 'Astragalus hallii A. Gray', 3.82, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (47, 'Tall Ironweed', 'Vernonia angustifolia Michx.', 69.42, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (48, 'Bahama Sachsia', 'Sachsia polycephala Griseb.', 51.16, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (49, 'Hybrid Willow', 'Salix ×princeps-ourayi L. Kelso', 44.53, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (50, 'Blisterwort', 'Ranunculus recurvatus Poir.', 62.24, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (51, 'Jesup''s Hawthorn', 'Crataegus jesupii Sarg.', 31.94, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (52, 'Caribbean Dot Lichen', 'Arthonia caribaea (Ach.) A. Massal.', 37.63, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (53, 'Retama Prieta', 'Senna polyphylla (Jacq.) Irwin & Barneby', 34.17, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (54, 'Streblus', 'Streblus Lour.', 15.12, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (55, 'Blemished Lichen', 'Phlyctis (Wallr.) Flotow', 10.17, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (56, 'American Waterwort', 'Elatine americana (Pursh) Arn.', 40.76, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (57, 'Flypoison', 'Amianthium muscitoxicum (Walter) A. Gray', 89.04, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (58, 'Broadleaf MonkeyfloresColas.FLOWER', 'Mimulus latifolius A. Gray', 51.29, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (59, 'Hartweg''s Paspalum', 'Paspalum hartwegianum Fourn.', 71.3, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (60, 'Grimmia Dry Rock Moss', 'Grimmia funalis (Schwägr.) Bruch & Schimp.', 75.82, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (61, 'Fijian Sawsedge', 'Gahnia vitiensis Rendle', 54.63, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (62, 'Rinodina Lichen', 'Rinodina olivaceobrunnea C.W. Dodge & Baker', 31.74, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (63, 'Indian Swampweed', 'Hygrophila polysperma (Roxb.) T. Anderson', 53.5, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (64, 'Pricklyfruit Bur Cucumber', 'Sicyos hispidus Hillebr.', 95.06, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (65, 'Hammock Bog Orchid', 'Habenaria distans Griseb.', 63.8, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (66, 'Davidson''s Saltbush', 'Atriplex pacifica A. Nelson', 27.68, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (67, 'Hansen''s Cinquefoil', 'Potentilla glandulosa Lindl. ssp. hansenii (Greene) D.D. Keck', 73.84, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (68, 'Sphagnum', 'Sphagnum obtusum Warnst.', 42.55, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (69, 'Rabbit-tobacco', 'Pseudognaphalium obtusifolium (L.) Hilliard & B.L. Burtt ssp. saxicola (Fassett) Kartesz', 35.92, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (70, 'Common Mallow', 'Malva neglecta Wallr.', 36.58, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (71, 'Bayhops', 'Ipomoea pes-caprae (L.) R. Br.', 10.8, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (72, 'Hairy Horsebrush', 'Tetradymia comosa A. Gray', 94.77, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (73, 'Stiff Clubmoss', 'Lycopodium annotinum L.', 41.88, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (74, 'Purple Bedstraw', 'Galium latifolium Michx.', 53.52, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (75, 'Forest Clover', 'Trifolium breweri S. Watson', 47.0, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (76, 'Oahu Melicope', 'Melicope oahuensis (Levl.) T.G. Hartley & B.C. Stone', 20.75, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (77, 'Clausena', 'Clausena Burm. f.', 75.75, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (78, 'Striped Cottonthorn', 'Tetradymia argyraea Munz & Roos', 34.86, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (79, 'Spider Milkweed', 'Asclepias asperula (Decne.) Woodson ssp. asperula', 52.28, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (80, 'Needleleaf Bluet', 'Houstonia acerosa (A. Gray) A. Gray ex Benth. & Hook. f. var. acerosa', 85.08, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (81, 'Jeweled Stenogyne', 'Stenogyne oxygona O. Deg. & Sherff', 7.68, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (82, 'Northern Bog Violet', 'Viola nephrophylla Greene', 64.38, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (83, 'Byssoloma Lichen', 'Byssoloma subdiscordans (Nyl.) P. James', 7.88, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (84, 'Rough Cocklebur', 'Xanthium strumarium L. var. strumarium', 58.34, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (85, 'Elliott''s Milkpea', 'Galactia elliottii Nutt.', 99.01, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (86, 'Jojo', 'Pfaffia grandiflora (Hook.) R.E. Fries', 17.59, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (87, 'Little Sagebrush', 'Artemisia arbuscula Nutt.', 80.35, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (88, 'Ovate Pterygoneurum Moss', 'Pterygoneurum ovatum (Hedw.) Dix.', 78.77, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (89, 'Creeping Snowberry', 'Symphoricarpos mollis Nutt.', 52.7, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (90, 'Del Norte Manzanita', 'Arctostaphylos nortensis P.V. Wells', 16.32, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (91, 'Fitch''s Hedgehog Cactus', 'Echinocereus reichenbachii (Terscheck ex Walp.) hort ex Haage ssp. fitchii (Britton & Rose) N.P. Taylor', 13.01, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (92, 'Placidiopsis Lichen', 'Placidiopsis Beltr.', 99.57, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (93, 'Edwards'' Starwort', 'Stellaria ciliatosepala Trautv.', 14.13, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (94, 'Giant Salvinia', 'Salvinia herzogii de la Sota', 76.61, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (95, 'Giant Dogwood', 'Cornus controversa Hemsl. ex Prain', 99.83, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (96, 'Creeping Redflush', 'Lampranthus multiradiatus (Jacq.) N.E. Br.', 35.35, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (97, 'Narrowleaf Soap Plant', 'Chlorogalum angustifolium Kellogg', 89.26, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (98, 'Rose Meadowsweet', 'Spiraea splendens Baumann ex K. Koch', 87.19, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (99, 'Torrey''s Rush', 'Juncus torreyi Coville', 67.5, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values (100, 'Cancer-root', 'Conopholis Wallr.', 20.99, 'error: Field ''“floresColas.COLOR”'' not found');
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values ('#680471', 'Red', 'Poaceae', null, null);
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values ('#253ccc', 'Green', 'Solanaceae', null, null);
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values ('#29961e', 'Violet', 'Fabaceae', null, null);
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values ('#5752dc', 'Blue', 'Fabaceae', null, null);
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values ('#fae6c1', 'Teal', 'Scrophulariaceae', null, null);
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values ('#70ff0d', 'Turquoise', 'Asteraceae', null, null);
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values ('#39b8a8', 'Yellow', 'Clusiaceae', null, null);
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values ('#a5b3c1', 'Maroon', 'Rutaceae', null, null);
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values ('#777fa2', 'Fuscia', 'Anacardiaceae', null, null);
insert into floresColas.FLOWER (code, name, description, price, floresColas.COLOR) values ('#6f6919', 'Fuscia', 'Calymperaceae', null, null);


create table floresColas.SALE (
	username INT,
	floresColas.FLOWER_code VARCHAR(50),
	quantity VARCHAR(50),
	price VARCHAR(50),
	date VARCHAR(50),
	ip_address VARCHAR(20)
);
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (1, 'Jayne', 'Obern', 'jobern0@narod.ru', 'Female', '187.206.220.118');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (2, 'Arri', 'Melby', 'amelby1@forbes.com', 'Male', '200.128.214.228');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (3, 'Sol', 'Breawood', 'sbreawood2@hc360.com', 'Male', '88.134.144.130');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (4, 'Raven', 'Berryann', 'rberryann3@goodreads.com', 'Female', '109.243.129.42');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (5, 'Opal', 'Daldan', 'odaldan4@odnoklassniki.ru', 'Female', '80.91.84.2');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (6, 'Jared', 'Wilflinger', 'jwilflinger5@reuters.com', 'Bigender', '26.229.109.195');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (7, 'Dud', 'Pimmocke', 'dpimmocke6@cam.ac.uk', 'Male', '102.191.63.49');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (8, 'Quentin', 'Showt', 'qshowt7@yellowbook.com', 'Female', '223.153.5.201');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (9, 'Lewie', 'Binton', 'lbinton8@unicef.org', 'Male', '54.129.23.172');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (10, 'Ferdinande', 'Van Waadenburg', 'fvanwaadenburg9@google.com', 'Female', '170.168.5.177');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (11, 'Waring', 'Johnigan', 'wjohnigana@yandex.ru', 'Male', '41.207.166.62');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (12, 'Baird', 'Domonkos', 'bdomonkosb@yolasite.com', 'Male', '184.47.2.82');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (13, 'Krissie', 'Duncanson', 'kduncansonc@edublogs.org', 'Female', '92.3.221.3');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (14, 'Sibyl', 'Saltern', 'ssalternd@vimeo.com', 'Female', '234.184.218.22');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (15, 'Elston', 'Slatter', 'eslattere@army.mil', 'Male', '165.211.114.120');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (16, 'Dukey', 'Tocher', 'dtocherf@imageshack.us', 'Male', '52.17.181.191');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (17, 'Freddi', 'Andrzejewski', 'fandrzejewskig@china.com.cn', 'Female', '153.101.247.117');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (18, 'Kiersten', 'Wheeldon', 'kwheeldonh@aol.com', 'Female', '109.15.204.29');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (19, 'Genovera', 'McCarly', 'gmccarlyi@netlog.com', 'Female', '99.191.31.251');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (20, 'Carmita', 'Shervil', 'cshervilj@sciencedaily.com', 'Female', '197.18.216.53');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (21, 'Calida', 'Rearie', 'creariek@ca.gov', 'Bigender', '193.120.153.12');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (22, 'Hollis', 'Edgington', 'hedgingtonl@foxnews.com', 'Male', '174.246.150.19');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (23, 'Perren', 'Boxe', 'pboxem@homestead.com', 'Male', '108.242.185.199');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (24, 'Gwen', 'Annes', 'gannesn@yahoo.com', 'Female', '212.30.76.177');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (25, 'Mindy', 'Hargreave', 'mhargreaveo@cnet.com', 'Female', '120.205.175.40');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (26, 'Ursala', 'Broady', 'ubroadyp@biglobe.ne.jp', 'Female', '102.251.17.159');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (27, 'Cecelia', 'Schukert', 'cschukertq@naver.com', 'Female', '114.182.247.9');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (28, 'Abdul', 'Fairpool', 'afairpoolr@opera.com', 'Male', '127.43.139.4');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (29, 'Tally', 'Trevers', 'ttreverss@slate.com', 'Female', '148.30.239.102');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (30, 'Florie', 'Kennerley', 'fkennerleyt@goo.gl', 'Female', '184.232.191.130');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (31, 'Alaster', 'Ollerenshaw', 'aollerenshawu@omniture.com', 'Male', '242.239.22.149');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (32, 'Callida', 'Bispo', 'cbispov@devhub.com', 'Female', '109.37.178.181');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (33, 'Janek', 'Blamey', 'jblameyw@ning.com', 'Male', '223.190.42.203');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (34, 'Trefor', 'Cole', 'tcolex@chronoengine.com', 'Male', '109.102.21.89');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (35, 'Fin', 'Bon', 'fbony@webs.com', 'Male', '95.32.140.222');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (36, 'Wait', 'Prinett', 'wprinettz@mayoclinic.com', 'Male', '65.25.237.203');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (37, 'Briggs', 'Serjeant', 'bserjeant10@blinklist.com', 'Male', '18.145.99.206');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (38, 'Kalindi', 'Calken', 'kcalken11@icq.com', 'Female', '160.133.124.220');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (39, 'Chloris', 'Dentith', 'cdentith12@ed.gov', 'Female', '26.74.117.215');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (40, 'Shel', 'Few', 'sfew13@youtu.be', 'Female', '153.79.38.103');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (41, 'Kizzie', 'Duff', 'kduff14@arstechnica.com', 'Female', '72.194.41.177');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (42, 'Nestor', 'Do', 'ndo15@domainmarket.com', 'Male', '77.79.37.115');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (43, 'Calley', 'Cicero', 'ccicero16@google.nl', 'Female', '94.86.142.93');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (44, 'Earle', 'Foy', 'efoy17@linkedin.com', 'Male', '44.130.60.39');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (45, 'Major', 'Carverhill', 'mcarverhill18@dion.ne.jp', 'Male', '48.126.69.246');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (46, 'Charmain', 'Mitchelhill', 'cmitchelhill19@mayoclinic.com', 'Female', '10.1.12.158');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (47, 'Nicolea', 'Iwanicki', 'niwanicki1a@weebly.com', 'Female', '184.239.56.154');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (48, 'Burg', 'Grundy', 'bgrundy1b@feedburner.com', 'Male', '91.51.133.219');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (49, 'Haskel', 'Stear', 'hstear1c@exblog.jp', 'Male', '220.250.74.150');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (50, 'Julianne', 'Gerrets', 'jgerrets1d@dailymotion.com', 'Female', '75.1.254.132');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (51, 'Gertrudis', 'Van de Castele', 'gvandecastele1e@reference.com', 'Female', '40.194.9.187');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (52, 'Jannelle', 'Keasley', 'jkeasley1f@huffingtonpost.com', 'Female', '84.164.27.115');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (53, 'Brennan', 'Monaghan', 'bmonaghan1g@quantcast.com', 'Male', '212.72.173.17');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (54, 'Mala', 'Byfford', 'mbyfford1h@bluehost.com', 'Female', '15.209.131.216');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (55, 'Candi', 'Levine', 'clevine1i@ox.ac.uk', 'Female', '120.77.32.98');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (56, 'Ansley', 'Roskam', 'aroskam1j@theatlantic.com', 'Female', '1.41.33.99');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (57, 'Llywellyn', 'Romanski', 'lromanski1k@opera.com', 'Male', '39.121.17.101');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (58, 'Pennie', 'Stammer', 'pstammer1l@va.gov', 'Male', '100.92.110.203');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (59, 'Quintus', 'Bent', 'qbent1m@tripod.com', 'Polygender', '226.4.104.142');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (60, 'Malissia', 'McCullouch', 'mmccullouch1n@blog.com', 'Female', '12.10.81.221');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (61, 'Wyndham', 'Gatiss', 'wgatiss1o@shop-pro.jp', 'Male', '247.95.145.216');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (62, 'Chicky', 'MacGillivray', 'cmacgillivray1p@state.gov', 'Female', '246.140.183.24');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (63, 'Ludvig', 'Messier', 'lmessier1q@e-recht24.de', 'Male', '31.71.18.17');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (64, 'Jenilee', 'Zorener', 'jzorener1r@linkedin.com', 'Genderfluid', '70.195.11.70');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (65, 'Hedwig', 'Gaskamp', 'hgaskamp1s@printfriendly.com', 'Genderqueer', '90.12.174.217');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (66, 'Mylo', 'Goulston', 'mgoulston1t@unc.edu', 'Male', '155.138.239.196');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (67, 'Polly', 'Huriche', 'phuriche1u@gov.uk', 'Female', '251.147.164.105');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (68, 'Etan', 'Withey', 'ewithey1v@ameblo.jp', 'Male', '16.89.78.254');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (69, 'Currie', 'Wigmore', 'cwigmore1w@plala.or.jp', 'Male', '73.110.233.186');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (70, 'Gayleen', 'Deakes', 'gdeakes1x@jimdo.com', 'Bigender', '59.82.144.125');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (71, 'Barrie', 'Lockett', 'blockett1y@baidu.com', 'Female', '88.200.231.245');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (72, 'Elissa', 'Farrar', 'efarrar1z@csmonitor.com', 'Female', '195.40.28.38');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (73, 'Craggie', 'Bygrove', 'cbygrove20@studiopress.com', 'Male', '107.239.84.195');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (74, 'Elka', 'Blodget', 'eblodget21@springer.com', 'Polygender', '52.239.138.74');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (75, 'Spense', 'Barlass', 'sbarlass22@businessweek.com', 'Male', '148.174.32.64');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (76, 'Belva', 'Minillo', 'bminillo23@de.vu', 'Female', '46.218.112.39');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (77, 'Patrick', 'Birdfield', 'pbirdfield24@mayoclinic.com', 'Male', '190.202.169.208');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (78, 'Trudi', 'Luciani', 'tluciani25@biglobe.ne.jp', 'Female', '185.174.155.243');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (79, 'Gray', 'Trolley', 'gtrolley26@theatlantic.com', 'Male', '166.154.112.221');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (80, 'Adelle', 'Bartleet', 'abartleet27@drupal.org', 'Female', '112.24.76.24');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (81, 'Miguel', 'Kingdom', 'mkingdom28@tiny.cc', 'Male', '84.24.139.208');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (82, 'Billy', 'Grandham', 'bgrandham29@bloomberg.com', 'Female', '32.207.188.41');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (83, 'Constantino', 'Jose', 'cjose2a@ycombinator.com', 'Male', '182.46.175.183');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (84, 'Renato', 'Thomas', 'rthomas2b@wp.com', 'Male', '148.220.25.163');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (85, 'Abbey', 'Vasic', 'avasic2c@timesonline.co.uk', 'Male', '176.39.82.52');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (86, 'Roy', 'Kettles', 'rkettles2d@arizona.edu', 'Male', '17.22.1.121');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (87, 'Hendrik', 'Bellinger', 'hbellinger2e@cam.ac.uk', 'Male', '102.76.59.171');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (88, 'Andrus', 'Peris', 'aperis2f@yellowpages.com', 'Male', '163.95.167.170');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (89, 'Currey', 'Littledike', 'clittledike2g@wiley.com', 'Agender', '18.143.56.89');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (90, 'Phoebe', 'Rizzetti', 'prizzetti2h@wunderground.com', 'Female', '25.251.43.248');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (91, 'Kelley', 'Armiger', 'karmiger2i@about.com', 'Male', '46.110.23.13');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (92, 'Trey', 'Milligan', 'tmilligan2j@nbcnews.com', 'Male', '44.38.115.160');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (93, 'Emalia', 'MacAndie', 'emacandie2k@huffingtonpost.com', 'Female', '128.62.65.90');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (94, 'Jamison', 'Struys', 'jstruys2l@boston.com', 'Male', '119.95.53.177');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (95, 'Stormi', 'Tissier', 'stissier2m@deliciousdays.com', 'Female', '72.201.238.59');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (96, 'Isabeau', 'Boxe', 'iboxe2n@hubpages.com', 'Female', '43.207.36.98');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (97, 'Gayel', 'MacKomb', 'gmackomb2o@etsy.com', 'Female', '247.182.102.218');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (98, 'Abelard', 'Aps', 'aaps2p@princeton.edu', 'Male', '8.149.65.176');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (99, 'Augusto', 'Claridge', 'aclaridge2q@shareafloresColas.SALE.com', 'Male', '219.90.37.211');
insert into floresColas.SALE (username, floresColas.FLOWER_code, quantity, price, date, ip_address) values (100, 'Danielle', 'Presnall', 'dpresnall2r@weibo.com', 'Female', '67.79.130.111');
